name: CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  check-commits:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v2
      with:
        # Fetch all history
        fetch-depth: 0

    - name: Check commit messages
      run: |
        scripts/check-commits.sh ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}

  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Shellcheck
      run: |
        shellcheck install/*.sh scripts/*.sh

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile

    - name: Lint
      run: |
        yarn lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
        postgres: [12]
        redis: [6]
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
      redis:
        image: redis:${{ matrix.redis }}
        ports:
          - 6379:6379
    env:
      RCTF_DATABASE_URL: postgres://postgres:password@localhost/rctf
      RCTF_REDIS_URL: redis://@localhost:6379/0
      RCTF_TOKEN_KEY: 32_byte_long_base64_encoded_value_for_token
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile

    - name: Create DB
      run: |
        psql postgres://postgres:password@localhost -c 'CREATE DATABASE rctf;'

    - name: Load configuration
      run: |
        cp test/conf-test.yaml conf.d

    - name: Run migrations
      run: |
        yarn migrate

    - name: Add data to DB
      run: |
        psql "$RCTF_DATABASE_URL" -c $'INSERT INTO challenges (id, data) VALUES (\'id\', \'{"flag": "flag{good_flag}", "name": "name", "files": [], "author": "author", "points": {"max": 500, "min": 100}, "category": "category", "description": "description", "tiebreakEligible": true}\')'

    - name: Build
      run: |
        yarn build

    - name: Run tests
      run: |
        yarn test:report

    - name: Upload coverage reports
      uses: codecov/codecov-action@v1

  docker-build:
    runs-on: ubuntu-latest
    # TODO: handle tagging releases correctly
    if: github.ref == 'refs/heads/master'
    needs:
      - shellcheck
      - lint
      - test

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:

      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@3f83d7b89cb3b72c3cb1c57dd6faaa722bb5895c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@3a3bb3a81753dc99f090d24ee7e5343838b73a96
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
